FROM node:20-alpine

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer puerto de Vite
EXPOSE 5173

# Comando por defecto (puede ser sobrescrito en docker-compose)
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
